### ISSUE TITLE
PSQLException from Talend complonent iUpdateSpatialExtent

### ISSUE THREAD

**Issue by mhidas** [aodn/harvest_sql_library#10]
I'm testing a pipeline change on **4-nec-hob**, and got the following error in the talend log (/mnt/ebs/log/data-services/ABOS_ASFS/IMOS_ABOS-ASFS_CFMST_20111125T010000Z_SOFS_FV02_SOFS-2-2011_END-20120722T220000Z_C-20170207T023902Z.nc.KR8Jfc.20170208-151513.log):

```
Going to process a total of '1' files
Processing slice with '1' files
Preparing file '/mnt/ebs/tmp/IMOS_ABOS-ASFS_CFMST_20111125T010000Z_SOFS_FV02_SOFS-2-2011_END-20120722T220000Z_C-20170207T023902Z.nc.KR8Jfc,IMOS/ABOS/ASFS/SOFS/Surface_fluxes/IMOS_ABOS-ASFS_CFMST_20111125T010000Z_SOFS_FV02_SOFS-2-2011_END-20120722T220000Z_C-20170207T023902Z.nc' in temp dir '/tmp/d20170208-3405-1zailb'
ADD '/mnt/ebs/tmp/IMOS_ABOS-ASFS_CFMST_20111125T010000Z_SOFS_FV02_SOFS-2-2011_END-20120722T220000Z_C-20170207T023902Z.nc.KR8Jfc' => 'IMOS/ABOS/ASFS/SOFS/Surface_fluxes/IMOS_ABOS-ASFS_CFMST_20111125T010000Z_SOFS_FV02_SOFS-2-2011_END-20120722T220000Z_C-20170207T023902Z.nc'
'abos_sofs_fl-abos_sofs_fl': ["IMOS/ABOS/ASFS/SOFS/Surface_fluxes/IMOS_ABOS-ASFS_CFMST_20111125T010000Z_SOFS_FV02_SOFS-2-2011_END-20120722T220000Z_C-20170207T023902Z.nc"]
Executing '/mnt/ebs/talend/jobs/abos_sofs_fl-abos_sofs_fl/java/ABOS_SOFS_surfaceflux_harvester/ABOS_SOFS_surfaceflux_harvester_run.sh --context_param paramFile="/mnt/ebs/talend/jobs/abos_sofs_fl-abos_sofs_fl/etc/abos_sofs_fl-abos_sofs_fl.conf" --context_param base=/tmp/d20170208-3405-1zailb --context_param fileList=/tmp/harvester_file_list20170208-3405-1rbnk5v --context_param logDir=/tmp/d20170208-3405-1txd8dt' for '["IMOS/ABOS/ASFS/SOFS/Surface_fluxes/IMOS_ABOS-ASFS_CFMST_20111125T010000Z_SOFS_FV02_SOFS-2-2011_END-20120722T220000Z_C-20170207T023902Z.nc"]'
INFO 2/8/17 3:15 PM:liquibase: Successfully acquired change log lock
INFO 2/8/17 3:15 PM:liquibase: Reading from abos_sofs_fl.databasechangelog
INFO 2/8/17 3:15 PM:liquibase: Reading from abos_sofs_fl.databasechangelog
INFO 2/8/17 3:15 PM:liquibase: Successfully released change log lock
INFO 2/8/17 3:15 PM:liquibase: Successfully acquired change log lock
INFO 2/8/17 3:15 PM:liquibase: Reading from abos_sofs_fl.databasechangelog
INFO 2/8/17 3:15 PM:liquibase: Reading from abos_sofs_fl.databasechangelog
INFO 2/8/17 3:15 PM:liquibase: Successfully released change log lock
Exception in component iUpdateSpatialExtent_1
org.postgresql.util.PSQLException: ERROR: upper bound of FOR loop cannot be null
  Where: PL/pgSQL function add_id_to_polygons(text) line 9 at FOR with integer loop variable
PL/pgSQL function boundingpolygonasgml3(text,text,text,double precision) line 7 at assignment
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283)
        at abos_sofs_surface_fluxes.updatemetadata_0_1.UpdateMetadata.iUpdateSpatialExtent_1Process(UpdateMetadata.java:561)
        at abos_sofs_surface_fluxes.updatemetadata_0_1.UpdateMetadata.runJobInTOS(UpdateMetadata.java:1206)
        at abos_sofs_surface_fluxes.updatemetadata_0_1.UpdateMetadata.runJob(UpdateMetadata.java:1037)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.tRunJob_6Process(ABOS_SOFS_surfaceflux_harvester.java:2671)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.tRunJob_4Process(ABOS_SOFS_surfaceflux_harvester.java:2541)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.iNewOrModifiedFileList_1Process(ABOS_SOFS_surfaceflux_harvester.java:2385)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.iDeletedFileList_1Process(ABOS_SOFS_surfaceflux_harvester.java:2035)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.iPostgresqlDbUpdate_1Process(ABOS_SOFS_surfaceflux_harvester.java:1700)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.iUpdateIndex_1Process(ABOS_SOFS_surfaceflux_harvester.java:1249)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.runJobInTOS(ABOS_SOFS_surfaceflux_harvester.java:4477)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.main(ABOS_SOFS_surfaceflux_harvester.java:4269)
Exception in component tRunJob_6
java.lang.RuntimeException: Child job running failed
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.tRunJob_6Process(ABOS_SOFS_surfaceflux_harvester.java:2682)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.tRunJob_4Process(ABOS_SOFS_surfaceflux_harvester.java:2541)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.iNewOrModifiedFileList_1Process(ABOS_SOFS_surfaceflux_harvester.java:2385)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.iDeletedFileList_1Process(ABOS_SOFS_surfaceflux_harvester.java:2035)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.iPostgresqlDbUpdate_1Process(ABOS_SOFS_surfaceflux_harvester.java:1700)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.iUpdateIndex_1Process(ABOS_SOFS_surfaceflux_harvester.java:1249)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.runJobInTOS(ABOS_SOFS_surfaceflux_harvester.java:4477)
        at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.main(ABOS_SOFS_surfaceflux_harvester.java:4269)
2017-02-08 15:15:24;oLfDdU;oLfDdU;oLfDdU;3414;ABOS_SOFS_SURFACE_FLUXES;ABOS_SOFS_surfaceflux_harvester;_Cr0fYEzNEeOBHf4HoZ3aaA;1.0;Default;;begin;;

2017-02-08 15:17:12;oLfDdU;oLfDdU;oLfDdU;3414;ABOS_SOFS_SURFACE_FLUXES;ABOS_SOFS_surfaceflux_harvester;_Cr0fYEzNEeOBHf4HoZ3aaA;1.0;Default;;end;failure;108175

Talend harvester abos_sofs_fl-abos_sofs_fl: 1 file(s)  FAILED
Aborting operation
```

This happened when I started with an empty db schema (abos_sofs_fl) so maybe it's something to do with having only a single point geometry in there? I did try to put in a second file at a different location, but got the same error.

**Comment by mhidas** [comment]
@jonescc tells me this is likely an issue with the SQL function, not the Talend component.

**Comment by julian1** [comment]
@mhidas @jonescc I should have reviewed this a few months ago, when the problem was fresh in everyone's minds. Do we know why we would be calling this function with a null polygon in the first place?

**Comment by mhidas** [comment]
As far as I know we're not intentionally doing anything with null polygons, but I don't know the inner workings of this SQL function, or the Talend component that calls it.

**Comment by jonescc** [comment]
This harvester uses two Update spatial extent components hooked up to the one index.  Both are being triggered by the processing of a file but only one points to a table with data in it, so for the other, the postgres functions are being called on an empty table (i.e. null geometry).   This used to result in the spatial extent in the metadata being deleted if present until I made changes to add id's to polygons to make them valid gml.  This broke previous processing.
